INSERT INTO y_assortment_event_type 
VALUES('DOC_UPLOADED','Document is uploaded');
INSERT INTO y_assortment_event_type 
VALUES('DOC_UPLOAD_ERROR','Error');
INSERT INTO y_assortment_event_type 
VALUES('INIT_START','Initialize is started');
INSERT INTO y_assortment_event_type 
VALUES('INIT_END','Initialize is ended');
INSERT INTO y_assortment_event_type 
VALUES('DB_EXCEPTION','DB initiate exception');
INSERT INTO y_assortment_event_type 
VALUES('UNHANDLED_EXCEPTION','Unhandled client exception');
INSERT INTO y_assortment_event_type 
VALUES('DOC_ACCEPTED','Document is accepted');
INSERT INTO y_assortment_event_type 
VALUES('DOC_CREATED','Document is created');
INSERT INTO y_assortment_event_type 
VALUES('DOC_DELETED','Document is deleted');
INSERT INTO y_assortment_event_type 
VALUES('DOCS_READY','Documents are ready');
